# Generated by Django 5.1.3 on 2024-12-09 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Short_name', models.CharField(max_length=255)),
                ('Long_name', models.CharField(max_length=255)),
                ('Decan', models.CharField(max_length=255)),
                ('Phone_number', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'Кафедра',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Short_name', models.CharField(max_length=255)),
                ('Long_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Direction',
                'verbose_name_plural': 'Directions',
                'db_table': 'Направление',
            },
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('Phone_number', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
                'db_table': 'Родители',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'Предмет',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('Phone_number', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('Form', models.CharField(max_length=255)),
                ('Degree', models.CharField(max_length=255)),
                ('id_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('id_direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.direction')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'Группа',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Birthday', models.DateField()),
                ('Phone_number', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group')),
                ('id_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.parents')),
            ],
            options={
                'verbose_name': 'Personal Info',
                'verbose_name_plural': 'Personal Info',
                'db_table': 'Личная_информация',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam', models.IntegerField(blank=True, null=True)),
                ('Zachet', models.CharField(blank=True, max_length=255, null=True)),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.personalinfo')),
                ('id_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
            ],
            options={
                'verbose_name': 'Performance',
                'verbose_name_plural': 'Performances',
                'db_table': 'Успеваемость',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='id_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher'),
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
                ('id_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Subject',
                'verbose_name_plural': 'Teacher Subjects',
                'db_table': 'Преподаватель_Предмет',
            },
        ),
    ]
